# Generated by Django 4.2.13 on 2026-06-29 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(blank=True, default='', max_length=255)),
                ('pickup_location', models.CharField(blank=True, default='', max_length=255)),
                ('dropoff_location', models.CharField(blank=True, default='', max_length=255)),
                ('cycle_hours_used', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('trip_date', models.DateField(blank=True, null=True)),
                ('tractor_number', models.CharField(blank=True, default='', max_length=50)),
                ('trailer_number', models.CharField(blank=True, default='', max_length=50)),
                ('shipper_name', models.CharField(blank=True, default='', max_length=255)),
                ('route_coordinates', models.JSONField(blank=True, default=list)),
                ('markers', models.JSONField(blank=True, default=list)),
                ('logbook_days', models.JSONField(blank=True, default=list)),
                ('trip_summary', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trip',
                'verbose_name_plural': 'trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
