# Generated by Django 4.2.13 on 2026-06-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cycle_schedule',
            field=models.CharField(choices=[('60', '60-hour / 7-day'), ('70', '70-hour / 8-day')], default='70', max_length=2),
        ),
    ]
